id: PYSEC-0000-CVE-2023-25399
details: A refcounting issue which leads to potential memory leak was discovered in
  scipy commit 8627df31ab in Py_FindObjects() function.
affected:
- package:
    name: scipy
    ecosystem: PyPI
    purl: pkg:pypi/scipy
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 1.11.1
references:
- type: EVIDENCE
  url: https://github.com/scipy/scipy/issues/16235
- type: REPORT
  url: https://github.com/scipy/scipy/issues/16235
- type: FIX
  url: https://github.com/scipy/scipy/issues/16235
- type: ADVISORY
  url: https://github.com/scipy/scipy/issues/16235
- type: FIX
  url: https://github.com/scipy/scipy/pull/16397
- type: WEB
  url: http://www.square16.org/achievement/cve-2023-25399/
aliases:
- CVE-2023-25399
modified: "2023-07-11T19:14:00Z"
published: "2023-07-05T17:15:00Z"
